name: "r00st Auditable Builder"

on:
# debug:
#  workflow_dispatch:
  workflow_call:
    inputs:
      repository:
        description: 'Input user/repo'
        required: true
        type: string
      serial:
        description: 'Unique Serial Cache Id'
        required: true
        type: string
      use-features:
        description: 'Use features?'
        requires: true
        type: string
      use-cache:
        description: 'Use cache?'
        required: true
        default: true
        type: boolean
      use-locked:
        description: 'Use locked?'
        required: true
        default: true
        type: boolean        
      os:
        description: 'GitHub Runner'
        required: true
        type: string
      r00st-target:
        description: 'r00st Target'
        required: true
        type: string
      r00st:
        description: 'r00st Version'
        required: true
        type: string
      zig-version:
        description: 'Zig version'
        required: false
        default: 0.9.1
        type: string

jobs:

  r00st-builder:
    name: r00st ${{ inputs.repository }} @ ${{ inputs.serial }} for ${{ inputs.r00st-target }} on (${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
    env:
      TARGET_DIR: target/${{ inputs.r00st-target }}/release
      REPO_NORMAL: unknown-unknown
    steps:
      - name: Normalise repo
        shell: bash
        run: |
          REPO_NORMAL=$(echo ${{ inputs.repository }} | sed 's/\//-/')
          echo "REPO_NORMAL=$REPO_NORMAL" >> $GITHUB_ENV
      - name: Pull zig-helper
        if: ${{ contains(inputs.os, 'windows') == false }}
        uses: actions/checkout@v3
        with:
          repository: rinse-repeat/zig-gh-helper
          path: zig-helper
      - name: Environment ZIG (Non-Windows)
        if: ${{ contains(inputs.os, 'windows') == false }}
        shell: bash
        run: |
          source ./zig-helper/zig_map.sh
          zig_triplets_env $GITHUB_ENV ${{ inputs.r00st-target }}
          cat $GITHUV_ENV
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          
      - name: NIX Cache ZIG
        if: ${{ contains(inputs.os, 'windows') == false }}
        uses: actions/cache@v3
        with:
          key: zig-${{ env.ZIG_OS }}-${{ env.ZIG_ARCH }}-${{ inputs.zig-version }}-AAB
          path: ~/zig
#          path: ${{ env.HOME }}/zig/zig-${{ env.ZIG_OS }}-${{ env.ZIG_ARCH }}-${{ inputs.zig-version }}
          
      - name: Debug
        shell: bash
        run: |
          echo Home=$HOME
          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          find $HOME -type f -name cargo-auditable
          find $HOME -type d -name \*zig\*
          echo PWD=$PWD

# long live the zig.. or not
      - name: System
        if: ${{ startsWith(inputs.os, 'ubuntu') }}
        run: sudo apt update && sudo apt upgrade && sudo apt install -qq lld crossbuild-essential-arm64 crossbuild-essential-armhf

      ######################################################
      # r00st, C**o Tools - Auditable, r00st-audit-info
      #
      # https://github.com/r00st-secure-code/c**o-auditable
      #
      - name: Install r00st ${{ inputs }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.r00st }}
          override: true
          target: ${{ inputs.r00st-target }}
      - name: Cache Cargo Tools
        if: ${{ inputs.use-cache }}
        uses: actions/cache@v3
        with:
          key: cargo-tools-${{ inputs.os }}-20220827-000
          path: |
            ~/.cargo/bin/cargo-auditable
            ~/.cargo/bin/rust-audit-info
#      - name: ls
#        run: ls -laR $HOME/
      - name: Install Cargo Tools
        shell: bash
        run: |
          if [[ ! -f $HOME/.cargo/bin/cargo-auditable ]]; then
            cargo install cargo-auditable rust-audit-info
          fi
#      - name: Debug
#        shell: bash
#        run: |
#          echo Home=$HOME
#          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
#          ls -la ./
#          find $HOME -type f -name cargo-auditable
#          find $HOME -type d -name \*zig\*
#          echo PWD=$PWD
      #######################################################
      # Zig & Cross-Compiling
      #
      - name: .Cargo setup for Zig
        shell: bash
        run: |
          cat >~/zcc.sh <<EOF        
          #!/bin/sh
          $HOME/zig/zig cc -target ${{ env.ZIG_ARCH }}-${{ env.ZIG_OS }} \$@
          EOF
          cat ~/zcc.sh
          chmod a+xrs ~/zcc.sh
          cat >~/.cargo/config <<EOF
          #[target.x86_64-unknown-linux-musl]
          #linker = "$HOME/zcc.sh"
          [target.aarch64-unknown-linux-musl]
          linker = "aarch64-linux-gnu-gcc"
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          [target.armv7-unknown-linux-gnueabihf]
          linker = "arm-linux-gnueabihf-gcc"
          [target.armv7-unknown-linux-musleabihf]
          linker = "arm-linux-gnueabihf-gcc"
          [target.arm-unknown-linux-gnueabihf]
          linker = "arm-linux-gnueabihf-gcc"
          [target.arm-unknown-linux-musleabihf]
          linker = "arm-linux-gnueabihf-gcc"
          EOF
      ######################################################
      # Use serials:
      # PR-XXX-DATE
      # 
      - uses: Swatinem/rust-cache@v2
        if: ${{ inputs.use-cache }}
        with:
          key: ${{ inputs.os }}-${{ inputs.r00st-target }}-${{ inputs.repository }}-${{ inputs.serial }}-000

      - name: Build Auditable Build
        shell: bash
        run: |
          cargo auditable build --release --locked --features ${{ inputs.use-featres }} --bins --color always --target ${{ inputs.r00st-target }} --target-dir ${{ env.TARGET_DIR }}

#      - name: ls -laR (debug)
#        shell: bash
#        run: ls -laR target/
      ######################################################
      # Upload artifacts
      #
      # target/x86_64-unknown-linux-gnu/release/x86_64-unknown-linux-gnu - !!
      #
      - name: Upload artifact - ${{ inputs.repository }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.r00st-target }}
          path: |
            ${{ env.TARGET_DIR }}/${{ inputs.r00st-target }}/release
            !${{ env.TARGET_DIR }}/${{ inputs.r00st-target }}/release/build
            !${{ env.TARGET_DIR }}/${{ inputs.r00st-target }}/release/deps
            # .fingerprint .cargo-lock
            !${{ env.TARGET_DIR }}/${{ inputs.r00st-target }}/release/.*
            !${{ env.TARGET_DIR }}/${{ inputs.r00st-target }}/release/*.d
          retention-days: 1